### PR TITLE
Player params

### PR DESCRIPTION
**Pull request by compedit**

### CODE REVIEW

**Comment by compedit** [comment]
@mhoofman thoughts?

**Comment by mhoofman** [comment]
I like these changes. It cleans up a lot.

In regards to the player loading process change:

I'm wondering if there is a way to preserve the YouTube player object between renders. I don't think it should be necessary to re-create it with each render / change of url (I'm not sure how smart React is about this). The changing of URLs or videoIds can be done through the player API (player.loadVideoByUrl, player.loadVideoById) if it's already been loaded.

One way this could be done is to set the player in a global variable during componentDidMount. This is sort of how the YT docs explain how to work with the API. However, the component loses a lot of its association at that point.

**Comment by compedit** [comment]
That's the route I initially wanted to take with this, but AFAIK there isn't a way to load a new url while respecting `playerVars.autoplay set on initialization.

So after the initial render using `videoId` & `playerVars.autoplay`, the loading process had to be hijacked and some extra logic was needed to call either `loadVideoById` or `cueVideoById`, similar to what was [already in place](https://github.com/compedit/react-youtube/blob/master/index.js#L106). 

I suppose I can put a disclaimer to ignore setting `playerVars.autoplay` but then we start moving away from the existing player api even further

**Comment by shobith** [comment]
:+1:

I had to hack up something to access the player parameters as well.

Here's what I had done, but I like your aproach better: https://github.com/shobith/react-youtube/commits/master

**Comment by shobith** [comment]
This may not be the right place to ask this, but have either of you come across a widget like this: http://imgur.com/vidgif -- the things I'm looking for here is the "editor" overlay on the youtube video itself, can it be done with the iframe api?

**Comment by compedit** [comment]
Ah yeah I had thought about going that route but felt more comfortable just placing all those props into a single `opts` object.

This is pretty much ready for merging, I'm still exploring some other options though.

**Comment by compedit** [comment]
Going forwards with this for now, the added complexity wasn't worth it.

**Pull request merged**
