### PR TITLE
Relax react version

### PR DESCRIPTION
**Pull request by sanemat**
for react v0.13.x

### CODE REVIEW

**Comment by sanemat** [comment]
`^0.12.2` means `>=0.12.2 <0.13.0`,
`^0.13.0` means `>=0.13.0 <0.14.0`.
Do we need react v0.12.x support? What do you think?
https://docs.npmjs.com/misc/semver#prerelease-identifiers

**Comment by compedit** [comment]
Hmm, what about just `>=0.12.2`?

**Comment by sanemat** [comment]
`>=0.12.0` and sqashed :bowtie:

**Comment by compedit** [comment]
Legend, thanks & merged!

**Pull request merged**
